[build-system]
build-backend = "hatchling.build"
requires = [ "hatch-requirements-txt", "hatchling" ]

[project]
name = "marktplaats"
version = "0.3.0"
description = "A small Python package to request listings from marktplaats.nl"
readme = "README.md"
authors = [
  { name = "Jens de Ruiter", email = "me@jensderuiter.dev" },
]
requires-python = ">=3.7"
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]
dynamic = [ "dependencies" ]

urls.bugs = "https://github.com/jensjeflensje/marktplaats-py/issues"
urls.homepage = "https://github.com/jensjeflensje/marktplaats-py"

[tool.hatch.metadata.hooks.requirements_txt]
files = [ "requirements.txt" ]
