name: Run live tests
on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Install uv
        uses: astral-sh/setup-uv@4959332f0f014c5280e7eac8b70c90cb574c9f9b # v6
        with:
          enable-cache: true

      - name: Run live tests
        run: uv run pytest tests/test_live.py
