name: Run tests
on:
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['minimum', 'default']
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Install uv
        uses: astral-sh/setup-uv@4959332f0f014c5280e7eac8b70c90cb574c9f9b # v6
        with:
          enable-cache: true

      - name: Change python version
        if: matrix.python-version == 'minimum'
        run: |
          version=$(sed -n 's/^requires-python *= *[">=]*\([0-9.]*\).*/\1/p' pyproject.toml)
          uv python pin $version

      - name: Run tests
        run: uv run pytest
